/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Concours;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import services.ConcoursService;
import java.text.ParseException;

/**
 *
 * @author Hp
 */
public class ConcoursForm extends javax.swing.JInternalFrame {

    private ConcoursService cs;
    private DefaultTableModel model;
    private Object sdf;
    private static int id;
    private Object his;
    private Object DateDate;

    /**
     * Creates new form ConcoursForm
     */
    public ConcoursForm() {
        initComponents();
        this.setTitle("Gestion des Concours");
        cs = new ConcoursService();
        model = (DefaultTableModel) ListeConcours.getModel();
        load();
    }

    public void load() {
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format cohérent
        for (Concours c : cs.findAll()) {
            model.addRow(new Object[]{c.getId(), c.getIntitule(), sdf.format(c.getDate()), c.getLieu()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gestioncouncoues = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLieu = new javax.swing.JTextField();
        txtIntitule = new javax.swing.JTextField();
        bnAdd = new javax.swing.JButton();
        bndelete = new javax.swing.JButton();
        bnupdate = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        ListeC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeConcours = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Gestioncouncoues.setBackground(new java.awt.Color(255, 255, 255));
        Gestioncouncoues.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Concours"));

        jLabel1.setText("Intitule:");

        jLabel2.setText("Date:");

        jLabel3.setText("Lieu:");

        txtLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLieuActionPerformed(evt);
            }
        });

        txtIntitule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntituleActionPerformed(evt);
            }
        });

        bnAdd.setBackground(java.awt.SystemColor.textHighlight);
        bnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-ajouter-16.png"))); // NOI18N
        bnAdd.setText("Ajouter");
        bnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddActionPerformed(evt);
            }
        });

        bndelete.setBackground(new java.awt.Color(255, 51, 0));
        bndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-supprimer-16.png"))); // NOI18N
        bndelete.setText("surpprimer");
        bndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bndeleteActionPerformed(evt);
            }
        });

        bnupdate.setBackground(new java.awt.Color(0, 153, 0));
        bnupdate.setText("Modifier");
        bnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GestioncouncouesLayout = new javax.swing.GroupLayout(Gestioncouncoues);
        Gestioncouncoues.setLayout(GestioncouncouesLayout);
        GestioncouncouesLayout.setHorizontalGroup(
            GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestioncouncouesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIntitule, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtLieu)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(165, 324, Short.MAX_VALUE))
        );
        GestioncouncouesLayout.setVerticalGroup(
            GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestioncouncouesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bndelete)
                    .addGroup(GestioncouncouesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GestioncouncouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestioncouncouesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(GestioncouncouesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestioncouncouesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bnupdate)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ListeC.setBackground(new java.awt.Color(204, 204, 255));
        ListeC.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des Concours"));
        ListeC.setForeground(new java.awt.Color(255, 255, 255));

        ListeConcours.setBackground(new java.awt.Color(204, 204, 255));
        ListeConcours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id", "Intitule", "Date", "Lieu"
            }
        ));
        ListeConcours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeConcoursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeConcours);

        javax.swing.GroupLayout ListeCLayout = new javax.swing.GroupLayout(ListeC);
        ListeC.setLayout(ListeCLayout);
        ListeCLayout.setHorizontalGroup(
            ListeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListeCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        ListeCLayout.setVerticalGroup(
            ListeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gestioncouncoues, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListeC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Gestioncouncoues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIntituleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntituleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntituleActionPerformed

    private void bnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddActionPerformed
        String intitule = txtIntitule.getText().trim();
        String lieu = txtLieu.getText().trim();
        java.util.Date utilDate = txtDate.getDate();

        if (intitule.isEmpty() || lieu.isEmpty() || utilDate == null) {
            JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis !");
            return;
        }

        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        if (cs.create(new Concours(intitule, sqlDate, lieu))) {
            JOptionPane.showMessageDialog(this, "Concours ajouté avec succès !");
            load();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du concours !");
            
        }
    }//GEN-LAST:event_bnAddActionPerformed

    private void txtLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLieuActionPerformed

    private void bndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bndeleteActionPerformed
        int selectedRow = ListeConcours.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) model.getValueAt(selectedRow, 0);
            if (cs.delete(cs.findById(id))) {
                JOptionPane.showMessageDialog(this, "concours supprimé avec succès");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un concours");
        }
    }//GEN-LAST:event_bndeleteActionPerformed

    private void bnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnupdateActionPerformed

        int selectedRow = ListeConcours.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un concours !");
            return;
        }

        int id = (int) model.getValueAt(selectedRow, 0);
        String intitule = txtIntitule.getText().trim();
        String lieu = txtLieu.getText().trim();
        java.util.Date utilDate = txtDate.getDate();

        if (intitule.isEmpty() || lieu.isEmpty() || utilDate == null) {
            JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis !");
            return;
        }

        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        int response = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ce concours ?");
        if (response == JOptionPane.YES_OPTION) {
            Concours c = new Concours(id, intitule, sqlDate, lieu);
            if (cs.update(c)) {
                JOptionPane.showMessageDialog(this, "Concours modifié avec succès !");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification !");
            }
        }
    }//GEN-LAST:event_bnupdateActionPerformed

    private void ListeConcoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeConcoursMouseClicked
        int selectedRow = ListeConcours.getSelectedRow();
        if (selectedRow != -1) {
            try {
                // Récupération de l'ID
                id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

                // Récupération de l'intitulé et du lieu
                txtIntitule.setText(model.getValueAt(selectedRow, 1).toString());
                txtLieu.setText(model.getValueAt(selectedRow, 3).toString());

                // Gestion de la date
                Object value = model.getValueAt(selectedRow, 2); // Récupérer la valeur de la colonne "Date"
                if (value instanceof Date) {
                    txtDate.setDate((Date) value);
                } else if (value instanceof String) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    try {
                        Date date = sdf.parse((String) value);
                        txtDate.setDate(date);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(this, "Erreur de format de date !");
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la sélection du concours !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un concours !");
        }

    }//GEN-LAST:event_ListeConcoursMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gestioncouncoues;
    private javax.swing.JPanel ListeC;
    private javax.swing.JTable ListeConcours;
    private javax.swing.JButton bnAdd;
    private javax.swing.JButton bndelete;
    private javax.swing.JButton bnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtIntitule;
    private javax.swing.JTextField txtLieu;
    // End of variables declaration//GEN-END:variables

}
