/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.PopupMenu;


/**
 *
 * @author Hp
 */
public class MDIApplication extends javax.swing.JFrame {
    private PopupMenu grapheFrame;

    /**
     * Creates new form NewMDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des Concours");
        this.setExtendedState(MAXIMIZED_BOTH);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuConcour = new javax.swing.JMenuItem();
        MenuCandidat = new javax.swing.JMenuItem();
        ResultatAsMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuResultatPConcours = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        openMenuConcour.setMnemonic('o');
        openMenuConcour.setText("Concours");
        openMenuConcour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuConcourActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuConcour);

        MenuCandidat.setMnemonic('s');
        MenuCandidat.setText("Candidat");
        MenuCandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCandidatActionPerformed(evt);
            }
        });
        fileMenu.add(MenuCandidat);

        ResultatAsMenu.setMnemonic('a');
        ResultatAsMenu.setText("Resultat");
        ResultatAsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultatAsMenuActionPerformed(evt);
            }
        });
        fileMenu.add(ResultatAsMenu);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Filtrer ");

        cutMenuResultatPConcours.setMnemonic('t');
        cutMenuResultatPConcours.setText(" résultats par concours");
        cutMenuResultatPConcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuResultatPConcoursActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuResultatPConcours);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("statistique");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Taux de réussite par concours");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuConcourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuConcourActionPerformed
  
    ConcoursForm concoursFrame = new ConcoursForm(); 
    desktopPane.add(concoursFrame);
    concoursFrame.setVisible(true);  
    }//GEN-LAST:event_openMenuConcourActionPerformed

    private void MenuCandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCandidatActionPerformed
   CandidatFrom candidatFrame = new CandidatFrom();
   desktopPane.add(candidatFrame);
   candidatFrame.setVisible(true);

    }//GEN-LAST:event_MenuCandidatActionPerformed

    private void ResultatAsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultatAsMenuActionPerformed
        ResultatForm resultatFrame = new ResultatForm();
        desktopPane.add(resultatFrame);
        resultatFrame.setVisible(true);
    }//GEN-LAST:event_ResultatAsMenuActionPerformed

    private void cutMenuResultatPConcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuResultatPConcoursActionPerformed
  ResultatparConcoursForm rs =  new ResultatparConcoursForm();
        desktopPane.add(rs);
        rs.setVisible(true);      
    }//GEN-LAST:event_cutMenuResultatPConcoursActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
 GrapheForm grapheFrame = new GrapheForm(); // Création d'une nouvelle fenêtre du graphe
    desktopPane.add(grapheFrame); // Ajout au JDesktopPane
    grapheFrame.setVisible(true); // Affichage de la fenêtre        
    }//GEN-LAST:event_contentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MDIApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCandidat;
    private javax.swing.JMenuItem ResultatAsMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuResultatPConcours;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuConcour;
    // End of variables declaration//GEN-END:variables

    private void GrapheForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    

}
