/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Candidat;
import beans.Concours;
import beans.Resultat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.CandidatService;
import services.ConcoursService;
import services.ResultatService;




/**
 *
 * @author Hp
 */
public class ResultatForm extends javax.swing.JInternalFrame {

    private CandidatService cds;
    private ConcoursService cs;
    private ResultatService rs;
    private DefaultTableModel model;

    /**
     * Creates new form ResultatForm
     */
    public ResultatForm() {
        
         initComponents();
    rs = new ResultatService();
    cs = new ConcoursService();
    cds = new CandidatService();
    loadConcours();
    loadCandidat();
    loadResultats();
    model = (DefaultTableModel) listeResultat.getModel();
}

   
        
     final void loadConcours() {
        for (Concours c : cs.findAll()) {
            listeConcous.addItem(c);
        }
    }

    final void loadCandidat() {
      for (Candidat c : cds.findAll()) {
        listCandidat.addItem(c);
    }
}

    private void loadResultats() {
        try {
        model.setRowCount(0); // Clear the table before reloading
        for (Resultat r : rs.findAll()) {
            model.addRow(new Object[]{
                r.getConcours().getIntitule(),
                r.getCandidat().getNom() + " " + r.getCandidat().getPrenom(),
                r.getNote()
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des résultats: " + e.getMessage());
        
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        listeConcous = new javax.swing.JComboBox();
        listCandidat = new javax.swing.JComboBox();
        txtNote = new javax.swing.JTextField();
        bnenregistrer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeResultat = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des Resultat"));

        jLabel1.setText("Concours:");

        jLabel2.setText("Candidat:");

        jLabel3.setText("Note:");

        listeConcous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeConcousActionPerformed(evt);
            }
        });

        listCandidat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        listCandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCandidatActionPerformed(evt);
            }
        });

        txtNote.setBackground(new java.awt.Color(255, 204, 204));

        bnenregistrer.setBackground(new java.awt.Color(0, 153, 102));
        bnenregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-utilisateur-24.png"))); // NOI18N
        bnenregistrer.setText("Enregistrer ");
        bnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnenregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listCandidat, 0, 129, Short.MAX_VALUE)
                    .addComponent(listeConcous, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNote))
                .addGap(193, 193, 193)
                .addComponent(bnenregistrer)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(listeConcous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listCandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bnenregistrer)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des Resultat"));

        listeResultat.setBackground(new java.awt.Color(51, 102, 255));
        listeResultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "concours", "candidat", "Note"
            }
        ));
        jScrollPane1.setViewportView(listeResultat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnenregistrerActionPerformed
   
          Concours concours = (Concours) listeConcous.getSelectedItem();
    Candidat candidat = (Candidat) listCandidat.getSelectedItem();
    String noteStr = txtNote.getText().trim();

    if (concours == null) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un concours !");
        return;
    }
    if (candidat == null) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un candidat !");
        return;
    }
    if (noteStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer une note !");
        return;
    }

    float note;
    try {
        note = Float.parseFloat(noteStr);
        if (note < 0 || note > 20) {
            JOptionPane.showMessageDialog(this, "La note doit être comprise entre 0 et 20 !");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un nombre valide pour la note !");
        return;
    }

    if (rs.create(new Resultat(concours, candidat, note))) {
        JOptionPane.showMessageDialog(this, "Résultat bien enregistré !");
        loadResultats();
        txtNote.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Problème lors de l'enregistrement !");
    }
    }//GEN-LAST:event_bnenregistrerActionPerformed

    
    
    private void listeConcousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeConcousActionPerformed
    }//GEN-LAST:event_listeConcousActionPerformed

    private void listCandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCandidatActionPerformed
        
       
    }//GEN-LAST:event_listCandidatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnenregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listCandidat;
    private javax.swing.JComboBox listeConcous;
    private javax.swing.JTable listeResultat;
    private javax.swing.JTextField txtNote;
    // End of variables declaration//GEN-END:variables


   
    
}
